project:
  type: book

book:
  title: "Gender Egalitarianism and Gender Equality:\nHow Public Opinion Shapes Politics and Policy in Global Perspective"
  author: "Byung-Deuk Woo and Frederick Solt"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - introduction.qmd
    - /theory/theory.qmd
    - /measuring_egalitarianism/measuring_egalitarianism.qmd
    - /descriptive_representation/descriptive_representation.qmd
    - /policy_adoption/policy_adoption.qmd
    - /mexico/mexico.qmd
    - /korea/korea.qmd
    - conclusion.qmd
    - references.qmd

bibliography: gender-equality.bib

format:
  pdf:
    documentclass: scrbook
    linestretch: "1.5"
