# Appendices

\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}
\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)

knitr::opts_chunk$set(cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE)

# If `DCPOtools` is not yet installed:
# remotes::install_github("fsolt/DCPOtools")

# If development version of `DCPO` is not yet installed:
# remotes::install_github("fsolt/DCPO")

library(DCPOtools)
library(DCPO)
library(tidyverse)
library(glue)
library(countrycode)
library(patchwork)
library(modelsummary)
library(here)

set.seed(324)

oecd_countries <- c("Australia", "Austria", "Belgium",
                    "Canada", "Chile", "Colombia",
                    "Costa Rica", "Czechia", "Denmark",
                    "Estonia", "Finland", "France", 
                    "Germany", "Greece", "Hungary",
                    "Iceland", "Ireland", "Israel",
                    "Italy", "Japan", "South Korea",
                    "Latvia", "Lithuania", "Luxembourg",
                    "Mexico", "Netherlands", "New Zealand",
                    "Norway", "Poland", "Portugal", 
                    "Slovakia", "Slovenia", "Spain",
                    "Sweden", "Switzerland", "Turkey", 
                    "United Kingdom", "United States")
```

\pagebreak
## Appendix A: Survey Items Used to Estimate Public Gender Egalitarianism
```{r item_summary, cache = FALSE, cache.extra = tools::md5sum(here::here("data-raw", "dcpo_input_raw_public.csv"))}
surveys_pge <- read_csv(here("paper",
                             "measuring_egalitarianism",
                             "data-raw",
                             "surveys_pge.csv"),
                        col_types = "cccccnn")

dcpo_input_raw_pge <- read_csv(here("paper",
                                    "measuring_egalitarianism",
                                    "data",
                                    "dcpo_input_raw_pge.csv"),
                               col_types = "cdcddcd")

load(here::here("data", "item_results.rda"))

process_dcpo_input_raw <- function(dcpo_input_raw_df) {
  dcpo_input_raw_df %>% 
    with_min_yrs(2) %>% 
    with_min_cy(5) %>% 
    filter(year >= 1972) %>% 
    group_by(country) %>% 
    mutate(cc_rank = n()) %>% 
    ungroup() %>% 
    arrange(-cc_rank)
} 

dcpo_input_raw_pge1 <- process_dcpo_input_raw(dcpo_input_raw_pge)

items_summary <- dcpo_input_raw_pge1 %>%
  dplyr::select(country, year, item, survey) %>%
  separate_rows(survey, sep=",\\s+") %>% 
  distinct() %>%
  group_by(item) %>% 
  mutate(survey = str_extract(survey, "^[a-z]*"),
         all_surveys = paste0(unique(survey), collapse = ", ")) %>% 
  ungroup() %>% 
  distinct(country, year, item, .keep_all = TRUE) %>% 
  group_by(item) %>% 
  mutate(n_cy = n()) %>% 
  ungroup() %>%
  distinct(item, n_cy, all_surveys) %>% 
  left_join(surveys_pge %>%
              select(item, question_text) %>%
              distinct(item, .keep_all = TRUE),
            by = "item") %>% 
  left_join(alpha_results, by = "item") %>% 
  left_join(beta_results, by = "item") %>% 
  arrange(-n_cy)

```

```{r dcpo_items_table}
#| label: tbl-items

items_summary %>% 
  transmute(`Survey\nItem\nCode` = item,
            `Country-Years` = as.character(n_cy),
            `Question Text` = str_replace(question_text, "([^(]*)\\(.*", "\\1"),
            # `Response Categories` = response_categories,
            `Dispersion` = as.character(sprintf("%.2f", dispersion)),
            `Difficulties` = difficulties,
            `Survey Dataset Codes*` = all_surveys) %>% 
  modelsummary::datasummary_df(output = "kableExtra",
                               longtable = TRUE,
                               title = "Survey Items Used to Estimate Public Gender Egalitarianism Scores",
                               escape = FALSE) %>% 
  kableExtra::kable_styling(latex_options = c("repeat_header"),
                            font_size = 7) %>%
  kableExtra::column_spec(1, width = "7em") %>%
  kableExtra::column_spec(2, width = "4em") %>%
  kableExtra::column_spec(3, width = "16em") %>%
  # kableExtra::column_spec(3, width = "13em") %>%
  kableExtra::column_spec(4, width = "4em") %>%
  kableExtra::column_spec(c(5, 6), width = "8em") %>%
  kableExtra::footnote(symbol = "Survey dataset codes correspond to those used in the DCPOtools R package (Solt, Hu, and Tai 2019).")
```

\pagebreak
## Appendix B: Source Data Observations by Country and Year
```{r obs1, fig.cap = "Source Data Observations by Country and Year", fig.height = 7}
#| label: fig-obs1

dcpo_input_plot <- dcpo_input_raw_pge1 %>% 
  filter(country %in% oecd_countries) %>% 
  distinct(country, year, item, cc_rank) %>% 
  group_by(country, year) %>% 
  summarize(n = n(),
            cc_rank = mean(cc_rank)) %>% 
  ungroup() 

dcpo_input_plot %>%
  ggplot(aes(x = year, 
             y = forcats::fct_reorder(country, cc_rank),
             fill = n)) + 
  geom_tile() +
  scale_fill_steps(low = rev(hcl.colors(8, "inferno"))[1],
                   high = rev(hcl.colors(8, "inferno"))[8],
                   breaks =  seq(2, 16, 2),
                   show.limits = TRUE,
                   right = FALSE,
                   name = "Observations") +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(breaks=seq(1968, 2024, 4),
                     sec.axis = dup_axis()) +
  scale_y_discrete(position = "right") +
  theme(axis.text.x  = element_text(size = 6),
        axis.text.y  = element_text(size = 7),
        strip.background = element_rect(fill = "white", colour = "white"),
        strip.placement = "outside",
        legend.position = "bottom",
        # legend.position = c(0.13, 0.12),
        legend.background = element_rect(fill = "white", colour = NA))
```

